language: dart
dart:
  - dev
sudo: false
script: ./tool/travis.sh
dist: trusty
env:
  - LINTER_BOT=main
  - LINTER_BOT=benchmark

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
