name: linter
version: 0.0.3-dev
author: Dart Team <misc@dartlang.org>
description: Style linter for Dart.
homepage: https://github.com/dart-lang/linter
dependencies:
  analyzer: '>=0.25.0-dev.1<0.26.0'
  args: '>=0.12.1 <0.14.0'
  cli_util: '>=0.0.1 <0.1.0'
  glob: '>=1.0.3 <2.0.0'
  plugin: '<0.2.0'
  source_span: '>=1.0.2 <2.0.0'
  yaml: '>=2.1.2 <3.0.0'
dev_dependencies:
  markdown: '>=0.7.1+2 <0.8.0'
  mockito: '>=0.10.1 <0.11.0'
  test: '>=0.12.0 <0.13.0'
