name: linter

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: "linter ${{ matrix.linter-bot }}"
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    strategy:
      fail-fast: false
      matrix:
        linter-bot:
          - main
          - benchmark
          - pana_baseline
          - release

    steps:
      - uses: actions/checkout@v2

      - name: ./tool/travis.sh
        env:
          LINTER_BOT: ${{ matrix.linter-bot }}
        run: ./tool/travis.sh
