name: linter

on:
  schedule:
    # “At 00:00 (UTC) on Sunday.”
    - cron: '0 0 * * 0'
  pull_request:
  push:
    branches:
      - master

env:
  PUB_ENVIRONMENT: bot.github

jobs:
  build:
    name: ${{ matrix.linter-bot }}
    runs-on: ubuntu-latest
    container:
      image:  google/dart:dev
    strategy:
      fail-fast: false
      matrix:
        linter-bot:
          - main
          - release
          - pana_baseline
          - benchmark

    steps:
      - uses: actions/checkout@v2

      - name: pub get
        run: dart pub get

      - name: tool/travis.sh
        env:
          LINTER_BOT: ${{ matrix.linter-bot }}
        run: ./tool/travis.sh
      - name: upload coverage
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: var/lcov.info
